# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd6018533f517189f584e7b9cea60f9a1c206713d5a1afaa9cb157440ddffdfe929a63b850fa76aec115d883f7fd2c75071c85d9eb26c268d19ba646e4bcae4c

test:
  secret_key_base: bfbd29936708871758db739d22ce0a494c28029b4fc621567a49e6b882b03265af3059488521fc653beb76f591fa26a5451a91330e5b819cb4f05b886001e082

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
